/*
 * This source file was generated by the Gradle 'init' task
 */
package org.excelencryptor;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ExcelReader reader = new ExcelReader();
        try {
            reader.read("/Users/xafixav/Downloads/datafrscrap/Igreja.xlsx");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
