/*
 * This source file was generated by the Gradle 'init' task
 */
package org.excelencryptor;

import org.excelencryptor.service.ExcelMockCreator;
import org.excelencryptor.util.ExcelReader;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        ExcelReader reader = new ExcelReader("/Users/xafixav/Downloads/datafrscrap/Igreja.xlsx");
        try {
            reader.read();
        } catch (IOException e) {
            System.err.println("An error occurred while reading the Excel file: " + e.getMessage());
        }
    }
}
